project_id = "qqkxxquqdxyiqalhccmo"

[functions.send_whatsapp]
verify_jwt = false

[functions.whatsapp_webhook]
verify_jwt = false

[functions.public_agenda_disponibilidad]
verify_jwt = false

[functions.public_solicitar_turno]
verify_jwt = false
