-- Agregar el valor 'manager' al enum app_role
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'manager';

-- Permisos por defecto para el rol manager
INSERT INTO public.role_permissions (role, module, action, allowed)
VALUES
  ('manager', 'cobros',              'read',   true),
  ('manager', 'cobros',              'create', false),
  ('manager', 'cobros',              'update', false),
  ('manager', 'cobros',              'delete', false),
  ('manager', 'pacientes',           'read',   true),
  ('manager', 'pacientes',           'create', false),
  ('manager', 'pacientes',           'update', false),
  ('manager', 'pacientes',           'delete', false),
  ('manager', 'profesionales',       'read',   true),
  ('manager', 'profesionales',       'create', false),
  ('manager', 'profesionales',       'update', false),
  ('manager', 'profesionales',       'delete', false),
  ('manager', 'reportes',            'read',   true),
  ('manager', 'reportes',            'create', false),
  ('manager', 'reportes',            'update', false),
  ('manager', 'reportes',            'delete', false),
  ('manager', 'agenda',              'read',   false),
  ('manager', 'agenda',              'create', false),
  ('manager', 'agenda',              'update', false),
  ('manager', 'agenda',              'delete', false),
  ('manager', 'bloqueos_agenda',     'read',   false),
  ('manager', 'bloqueos_agenda',     'create', false),
  ('manager', 'bloqueos_agenda',     'update', false),
  ('manager', 'bloqueos_agenda',     'delete', false),
  ('manager', 'atenciones',          'read',   false),
  ('manager', 'atenciones',          'create', false),
  ('manager', 'atenciones',          'update', false),
  ('manager', 'atenciones',          'delete', false),
  ('manager', 'recetas_externas',    'read',   false),
  ('manager', 'recetas_externas',    'create', false),
  ('manager', 'recetas_externas',    'update', false),
  ('manager', 'recetas_externas',    'delete', false),
  ('manager', 'odontograma',         'read',   false),
  ('manager', 'odontograma',         'create', false),
  ('manager', 'odontograma',         'update', false),
  ('manager', 'odontograma',         'delete', false),
  ('manager', 'prestaciones',        'read',   false),
  ('manager', 'prestaciones',        'create', false),
  ('manager', 'prestaciones',        'update', false),
  ('manager', 'prestaciones',        'delete', false),
  ('manager', 'obras_sociales',      'read',   false),
  ('manager', 'obras_sociales',      'create', false),
  ('manager', 'obras_sociales',      'update', false),
  ('manager', 'obras_sociales',      'delete', false),
  ('manager', 'presupuestos',        'read',   false),
  ('manager', 'presupuestos',        'create', false),
  ('manager', 'presupuestos',        'update', false),
  ('manager', 'presupuestos',        'delete', false),
  ('manager', 'laboratorios',        'read',   false),
  ('manager', 'laboratorios',        'create', false),
  ('manager', 'laboratorios',        'update', false),
  ('manager', 'laboratorios',        'delete', false),
  ('manager', 'seguridad_usuarios',  'read',   false),
  ('manager', 'seguridad_usuarios',  'create', false),
  ('manager', 'seguridad_usuarios',  'update', false),
  ('manager', 'seguridad_usuarios',  'delete', false),
  ('manager', 'seguridad_perfiles',  'read',   false),
  ('manager', 'seguridad_perfiles',  'create', false),
  ('manager', 'seguridad_perfiles',  'update', false),
  ('manager', 'seguridad_perfiles',  'delete', false),
  ('manager', 'auditoria',           'read',   false),
  ('manager', 'auditoria',           'create', false),
  ('manager', 'auditoria',           'update', false),
  ('manager', 'auditoria',           'delete', false),
  ('manager', 'salud_bot',           'read',   false),
  ('manager', 'salud_bot',           'create', false),
  ('manager', 'salud_bot',           'update', false),
  ('manager', 'salud_bot',           'delete', false)
ON CONFLICT (role, module, action) DO NOTHING;
